apiVersion: v1
kind: Service
metadata:
  name: {{ include "checkout-svc.fullname" . }}
  labels:
    {{- include "checkout-svc.labels" . | nindent 4 }}
    driftguard.io/service-role: active
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "checkout-svc.selectorLabels" . | nindent 4 }}
