{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "payments-svc.fullname" . }}
  labels:
    {{- include "payments-svc.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "payments-svc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      driftguard.io/service-role: active
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
