apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkout-dev
  namespace: argocd
spec:
  project: driftguard
  source:
    repoURL: https://github.com/Arnazz10/DriftGuard.git
    targetRevision: main
    path: charts/checkout-svc
    helm:
      releaseName: checkout-svc
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

