apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-prod
  namespace: argocd
spec:
  project: driftguard
  source:
    repoURL: https://github.com/Arnazz10/DriftGuard.git
    targetRevision: main
    path: charts/payments-svc
    helm:
      releaseName: payments-svc
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

